language: generic
dist: xenial
sudo: required

install:
- wget -q -P /tmp https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
- sudo dpkg -i /tmp/packages-microsoft-prod.deb
- sudo rm /tmp/packages-microsoft-prod.deb
- export DEBIAN_FRONTEND=noninteractive
- sudo apt-get update
- sudo apt-get install -y powershell
  
script:
- bash test.sh
